version: 3.0

data: 
  indir: "data/raw/"
  
  transforms:
    format: "Title: {title}, Genres: {genres}, Sypnopsis: {sypnopsis}"

  persist_dir: "data/chroma_db/"
  embed_model: "all-MiniLM-L6-v2"

recommender:
  llm: "llama-3.1-8b-instant"
  temperature: 0.7